Ops 2476
Flaconi/docker-python pull request #4
Opened 2018-08-13 12:15 UTC by vikkasyousaf

2018-08-13 13:44 UTC, cytopia requested changes
Looks good, one minor typo in the URL to adjust.
 :+1:

2018-08-13 13:44 UTC, cytopia commented on README.md
> +[![Build Status](https://travis-ci.org/Flaconi/docker-python.svg?branch=master)](https://travis-ci.org/Flaconi/docker-python)
This is building on **travis.com**, not on **travis.org**

2018-08-13 13:44 UTC, cytopia commented
Please also rebase your branch, otherwise you won't be able to merge it here.

2018-08-15 11:28 UTC, vikkasyousaf reviewed
Typo mistake resolved in URL

2018-08-15 11:46 UTC, cytopia requested changes

2018-08-15 11:46 UTC, cytopia commented on README.md
> +[![Build Status](https://travis-ci.org/Flaconi/docker-python.svg?branch=master)](https://travis-ci.com/Flaconi/docker-python)
Still using `.org` instead of `.com`

2018-08-15 11:51 UTC, cytopia approved these changes

2018-08-15 12:39 UTC, merged